### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Lellansin** [DoubleSpout/node-threads-a-gogo2#6]
```
npm WARN engine tagg2@0.2.0: wanted: {"node":">:z=0.8.0"} (current: {"node":"0.12.2","npm":"2.11.0"})

> tagg2@0.2.0 preinstall /Users/Lellansin/Documents/workspace/node/threads/node_modules/tagg2
> node install.js

###########################################


thanks for choose tagg2 module to let node.js have multi threads functionally

tagg2 module support windows, linux, mac,make sure nodejs version must >=0.8.x

if have any problem, Contact me

qq:53822985,email:snoopyxdy@163.com

so enjoy it!


###########################################
/
> tagg2@0.2.0 install /Users/Lellansin/Documents/workspace/node/threads/node_modules/tagg2
> node-gyp rebuild

  CXX(target) Release/obj.target/threads_a_gogo/src/threads_a_gogo.o
../src/threads_a_gogo.cpp:86:3: error: unknown type name 'uv_async_t'
  uv_async_t async_watcher; //MUST be the first one 使用 libuv
  ^
../src/threads_a_gogo.cpp:166:41: error: unknown type name 'Arguments'; did you
      mean 'v8::internal::Arguments'?
static Handle<Value> require_file(const Arguments &args) //读取js文件
                                        ^~~~~~~~~
                                        v8::internal::Arguments
/Users/Lellansin/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cpp:168:14: error: calling a protected constructor of
      class 'v8::HandleScope'
        HandleScope scope;
                    ^
/Users/Lellansin/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
../src/threads_a_gogo.cpp:170:11: error: type 'const v8::internal::Arguments'
      does not provide a subscript operator
                if(!args[0]->IsString()){
                    ~~~~^~
../src/threads_a_gogo.cpp:171:54: error: no member named 'New' in 'v8::String'
                return ThrowException(Exception::TypeError(String::New("...
                                                           ~~~~~~~~^
../src/threads_a_gogo.cpp:174:27: error: member access into incomplete type
      'const v8::internal::Arguments'
        Local<Object> Gobj = args.This();
                                 ^
/Users/Lellansin/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: forward
      declaration of 'v8::internal::Arguments'
class Arguments;
      ^
../src/threads_a_gogo.cpp:176:60: error: no member named
      'GetPointerFromInternalField' in 'v8::Object'
        String::Utf8Value* dirname_p = (String::Utf8Value*) Gobj->GetPoi...
                                                            ~~~~  ^
../src/threads_a_gogo.cpp:182:59: error: no member named 'New' in 'v8::String'
        Local<Object> path_resolve_obj = Script::Compile(String::New(pat...
                                                         ~~~~~~~~^
../src/threads_a_gogo.cpp:186:66: error: no member named 'New' in 'v8::String'
        Local<Object> path_resolve_func = path_resolve_obj->Get(String::New("res...
                                                                ~~~~~~~~^
../src/threads_a_gogo.cpp:189:23: error: no member named 'New' in 'v8::String'
    argv[0] = String::New(dirname.c_str());
              ~~~~~~~~^
../src/threads_a_gogo.cpp:190:16: error: type 'const v8::internal::Arguments'
      does not provide a subscript operator
        argv[1] = args[0];
                  ~~~~^~
../src/threads_a_gogo.cpp:192:78: error: too few arguments to function call,
      single argument 'isolate' was not specified
  ...path_str_value = path_resolve_func->CallAsFunction(Object::New(), 2, argv);
                                                        ~~~~~~~~~~~ ^
/Users/Lellansin/.node-gyp/0.12.2/deps/v8/include/v8.h:2388:3: note: 'New'
      declared here
  static Local<Object> New(Isolate* isolate);
  ^
../src/threads_a_gogo.cpp:199:32: error: no member named 'New' in 'v8::String'
        char *file = readFile(String::New(path_str.c_str()));
                              ~~~~~~~~^
../src/threads_a_gogo.cpp:202:26: error: no member named 'New' in 'v8::String'
        Script::Compile(String::New(file))->Run();
                        ~~~~~~~~^
../src/threads_a_gogo.cpp:208:54: error: no member named 'New' in 'v8::String'
                return ThrowException(Exception::TypeError(String::New(e...
                                                           ~~~~~~~~^
../src/threads_a_gogo.cpp:211:15: error: no member named 'Close' in
      'v8::HandleScope'
        return scope.Close(Gobj);
               ~~~~~ ^
../src/threads_a_gogo.cpp:236:39: error: no member named
      'GetPointerFromInternalField' in 'v8::Object'
      thread= (typeThread*) receiver->GetPointerFromInternalField(0); //...
                            ~~~~~~~~  ^
../src/threads_a_gogo.cpp:265:34: error: unknown type name 'Arguments'; did you
      mean 'v8::internal::Arguments'?
static Handle<Value> Puts (const Arguments &args) {
                                 ^~~~~~~~~
                                 v8::internal::Arguments
/Users/Lellansin/.node-gyp/0.12.2/deps/v8/include/v8.h:127:7: note: 
      'v8::internal::Arguments' declared here
class Arguments;
      ^
../src/threads_a_gogo.cpp:268:15: error: calling a protected constructor of
      class 'v8::HandleScope'
  HandleScope scope;
              ^
/Users/Lellansin/.node-gyp/0.12.2/deps/v8/include/v8.h:816:13: note: declared
      protected here
  V8_INLINE HandleScope() {}
            ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/threads_a_gogo/src/threads_a_gogo.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Lellansin/Documents/workspace/node/threads/node_modules/tagg2
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "tagg2"
npm ERR! node v0.12.2
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE

npm ERR! tagg2@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tagg2@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the tagg2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls tagg2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Lellansin/Documents/workspace/node/threads/npm-debug.log
```

**Comment by anonymous530** [comment]
npm install tagg2   

gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.14393

npm ERR! tagg2@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tagg2@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the tagg2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tagg2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls tagg2
npm ERR! There is likely additional logging output above.

**Comment by ignaciozhuzhu** [comment]
D:\work\myProject\nodejsdemo\React-Nodejs-Project-Quickly-Start> npm install tagg2
npm WARN package.json react-nodejs-learn@1.0.0 No repository field.
npm WARN engine tagg2@0.2.0: wanted: {"node":">:z=0.8.0"} (current: {"node":"4.5.0","npm":"2.15.9"})

> tagg2@0.2.0 preinstall D:\work\myProject\nodejsdemo\React-Nodejs-Project-Quickly-Start\node_modules\tagg2
> node install.js

###########################################


thanks for choose tagg2 module to let node.js have multi threads functionally

tagg2 module support windows, linux, mac,make sure nodejs version must >=0.8.x

if have any problem, Contact me

qq:53822985,email:snoopyxdy@163.com

so enjoy it!


###########################################
/
> tagg2@0.2.0 install D:\work\myProject\nodejsdemo\React-Nodejs-Project-Quickly-Start\node_modules\tagg2
> node-gyp rebuild


D:\work\myProject\nodejsdemo\React-Nodejs-Project-Quickly-Start\node_modules\tagg2>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [D:\work\myProje
ct\nodejsdemo\React-Nodejs-Project-Quickly-Start\node_modules\tagg2\build\threads_a_gogo.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\work\myProject\nodejsdemo\React-Nodejs-Project-Quickly-Start\node_modules\tagg2
gyp ERR! node -v v4.5.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "tagg2"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code ELIFECYCLE

npm ERR! tagg2@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tagg2@0.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the tagg2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tagg2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls tagg2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\work\myProject\nodejsdemo\React-Nodejs-Project-Quickly-Start\npm-debug.log
